# Generated by Django 4.2.1 on 2023-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="total_sales",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="total_sales_amount",
            field=models.IntegerField(default=0),
        ),
    ]
