# Generated by Django 4.2.1 on 2023-06-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="profilepic.gif", upload_to="profile"),
        ),
    ]
